### PR TITLE
Add LSP Coordinate to override the JAR to use for the LSP

### PR DESCRIPTION
**Pull request by daddykotex**

### CODE REVIEW

**Comment by daddykotex** [comment]
Screen Shot 2022-07-14 at 14 12 13

**Comment by daddykotex** [comment]
anton is on the watch

**Comment by keynmol** [comment]
I misread the error on GHA :D 

The failure seems to be legit, related to the GHA action.

**Comment by daddykotex** [comment]
I guess there is no need to use this custom action as `yarn` seems to be available in the `ubuntu-latest` default

**Comment by daddykotex** [comment]
at least according to https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

**Comment by daddykotex** [comment]
Superseeded by: https://github.com/disneystreaming/vscode-smithy/pull/11

**Pull request closed without merging**
